
version: '3.8'

services:
  fire-hazard-api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    container_name: fire_hazard_api
    environment:
      - FLASK_ENV=production

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
