global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      #- targets: ['<FLASK_APP_HOST>:5000']  # Replace <FLASK_APP_HOST> with the actual host/IP
      #- targets: ['localhost:5000']
      - targets: ['fire-hazard-api:5000']

